// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5AuSmSXVeqtq_1DtV5baJgQppob27iA',
    appId: '1:1012477760277:web:154194a73608c414518f1c',
    messagingSenderId: '1012477760277',
    projectId: 'fir-project-f811e',
    authDomain: 'fir-project-f811e.firebaseapp.com',
    storageBucket: 'fir-project-f811e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFrCHVsuhHfCId-xQf3ovatC3EeKWOC0Q',
    appId: '1:1012477760277:android:f89dc1587abb2752518f1c',
    messagingSenderId: '1012477760277',
    projectId: 'fir-project-f811e',
    storageBucket: 'fir-project-f811e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxCvpt0v9X6JBNEMEIqjIYhC15BvFsd_4',
    appId: '1:1012477760277:ios:05a81d08655cc8f3518f1c',
    messagingSenderId: '1012477760277',
    projectId: 'fir-project-f811e',
    storageBucket: 'fir-project-f811e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxCvpt0v9X6JBNEMEIqjIYhC15BvFsd_4',
    appId: '1:1012477760277:ios:05a81d08655cc8f3518f1c',
    messagingSenderId: '1012477760277',
    projectId: 'fir-project-f811e',
    storageBucket: 'fir-project-f811e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5AuSmSXVeqtq_1DtV5baJgQppob27iA',
    appId: '1:1012477760277:web:c8c2b4f9c5d83939518f1c',
    messagingSenderId: '1012477760277',
    projectId: 'fir-project-f811e',
    authDomain: 'fir-project-f811e.firebaseapp.com',
    storageBucket: 'fir-project-f811e.firebasestorage.app',
  );
}
